spring:
  application:
    name: pos-order
  cloud:
    function:
      definition: createDeliver
    stream:
      function:
        bindings:
          createDeliver-out-0: deliver
      bindings:
        deliver:
          destination: deliver
server:
  port: 45903
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}