spring:
  application:
    name: pos-deliver
  cloud:
      function:
        definition: makeDelivery
      stream:
        function:
          bindings:
            makeDelivery-in-0: deliver
        # bindings:
        #   loan-declined:
        #     destination: loan-declined
        #   loan-approved:
        #     destination: loan-approved
        rabbit:
          bindings:
            deliver:
              consumer:
                declare-exchange: false
server:
  port: 45902
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}